name = "moe-counter"
main = "dist/worker.js"
compatibility_date = "2024-02-27"
workers_dev = false

[[routes]]
pattern = "moe-counter.lxchapu.com"
custom_domain = true

[build]
command = "npm run build"

[[d1_databases]]
binding = "DB"
database_name = "count"
database_id = "08323087-a0a9-44cb-a940-c82df8945a47"
