name = "moe-counter"
main = "dist/worker.js"
compatibility_date = "2024-02-27"
workers_dev = true

kv_namespaces = [
  { binding = "count", id = "d54a20641c5c4ef68c248c3a6173239e" }
]

[[routes]]
pattern = "moe-counter.lxchapu.com"
zone_name = "lxchapu.com"
custom_domain = true

[build]
command = "npm run build"